"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 20:22:51.009655
"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op  # noqa: F401


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bannedaccount',
    sa.Column('account_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_sha256')
    )
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ms_tenant_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('ms_object_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('terms_version', sa.Integer(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ms_tenant_id', 'ms_object_id', name='uq_user_ms_identity')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    op.create_table('authsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authsession_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_authsession_user_id'), ['user_id'], unique=False)

    op.create_table('eventseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('weekdays', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventseries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventseries_creator_id'), ['creator_id'], unique=False)

    op.create_table('floor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('floor_plan_svg', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_floor_building_id'), ['building_id'], unique=False)

    op.create_table('rulehit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rulehit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rulehit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rulehit_user_id'), ['user_id'], unique=False)

    op.create_table('userfavorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'favorite_user_id')
    )
    op.create_table('userhidden',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hidden_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hidden_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'hidden_user_id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('shape_ref', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('is_outdoor', sa.Boolean(), nullable=False),
    sa.Column('map_x', sa.Float(), nullable=True),
    sa.Column('map_y', sa.Float(), nullable=True),
    sa.Column('max_overlapping', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_floor_id'), ['floor_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('location_kind', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('online_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('majors', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_reason', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['eventseries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_starts_at'), ['starts_at'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('subject_user_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_user_id'), ['user_id'], unique=False)

    op.create_table('hiddenevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['eventseries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_hidden_event'),
    sa.UniqueConstraint('user_id', 'series_id', name='uq_hidden_series')
    )
    with op.batch_alter_table('hiddenevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hiddenevent_user_id'), ['user_id'], unique=False)

    op.create_table('moderationlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_event_id', sa.Integer(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_event_id'], ['event.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderationlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderationlog_created_at'), ['created_at'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'event_id', name='uq_report_once')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_event_id'), ['event_id'], unique=False)

    op.create_table('rsvp',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rsvp_event_id'), ['event_id'], unique=False)

    op.create_table('savedevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['eventseries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_saved_event'),
    sa.UniqueConstraint('user_id', 'series_id', name='uq_saved_series')
    )
    with op.batch_alter_table('savedevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savedevent_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savedevent_user_id'))

    op.drop_table('savedevent')
    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rsvp_event_id'))

    op.drop_table('rsvp')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_event_id'))

    op.drop_table('report')
    with op.batch_alter_table('moderationlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderationlog_created_at'))

    op.drop_table('moderationlog')
    with op.batch_alter_table('hiddenevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hiddenevent_user_id'))

    op.drop_table('hiddenevent')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_user_id'))

    op.drop_table('alert')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_starts_at'))
        batch_op.drop_index(batch_op.f('ix_event_series_id'))
        batch_op.drop_index(batch_op.f('ix_event_room_id'))
        batch_op.drop_index(batch_op.f('ix_event_ends_at'))
        batch_op.drop_index(batch_op.f('ix_event_creator_id'))

    op.drop_table('event')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_floor_id'))

    op.drop_table('room')
    op.drop_table('userhidden')
    op.drop_table('userfavorite')
    with op.batch_alter_table('rulehit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rulehit_user_id'))
        batch_op.drop_index(batch_op.f('ix_rulehit_created_at'))

    op.drop_table('rulehit')
    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floor_building_id'))

    op.drop_table('floor')
    with op.batch_alter_table('eventseries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventseries_creator_id'))

    op.drop_table('eventseries')
    with op.batch_alter_table('authsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authsession_user_id'))
        batch_op.drop_index(batch_op.f('ix_authsession_jti'))

    op.drop_table('authsession')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('building')
    op.drop_table('bannedaccount')
    # ### end Alembic commands ###
